### ISSUE TITLE
Console logging

### ISSUE THREAD

**Issue by ukdtom** [trakt/Plex-Trakt-Scrobbler#265] opened 2016-01-18 20:18 UTC
Any chance, that Console logging could be in the prefs?

And default switched off?

Kinda hard to trace stuff to console for other stuff, since Trakt is very "chatty" ;-)

**Comment by fuzeman** [comment] 2016-01-19 04:39
> Any chance, that Console logging could be in the prefs?

Honestly not sure what you mean by *console* logging, do you mean the usual plugin log files or are you talking about something else?

------------------------

There is "Logging" options in the preferences, changing these to "ERROR" should reduce the number of messages written to the log file.

**Comment by ukdtom** [comment] 2016-01-20 19:34
Well.....Logging to log files is great, but see a screen dump here from my console on my PMS box (QNAPx86)

https://gist.github.com/ukdtom/30c20496702986b74c0e

**Comment by fuzeman** [comment] 2016-01-22 02:06
Have you tried changing the "Logging" options in the preferences? from my tests these options change the console log level as well.

**Comment by ukdtom** [comment] 2016-01-22 20:00
Ohhh....and works, but not my point here.....

Point is, why log to console?

**Comment by fuzeman** [comment] 2016-01-22 21:59
Ohh.. I've never specifically enabled console logging, it must be caused by our other logger changes.

I'll have a look this weekend :smiley:

**Comment by ukdtom** [comment] 2016-01-22 22:01
Thanks mate ;-)

**Comment by fuzeman** [comment] 2016-01-25 04:30
This issue should be fixed on the "develop" branch, turns out it was just an option in the "Info.plist" file.

**Closed** 2016-01-25 04:30 UTC
Labels: bug

**Comment by ukdtom** [comment] 2016-01-25 20:25
And found it, and confirmed ;-)
