### ISSUE TITLE
Push error "MovieMatch has no attribute identifiiers"

### ISSUE THREAD

**Issue by miracle152004** [trakt/Plex-Trakt-Scrobbler#427] opened 2017-03-19 07:49 UTC
Hi,

I get the following error on sancing.
I can understand that the sync cannot add the file on which this is happening, but nothing is synced.
It should still sync the other files.
Also there should be a way for looking up which entry is responsible for this error.

Thans

best regards
miracle152004

**Comment by fuzeman** [comment] 2017-03-20 23:42
Duplicate of https://github.com/trakt/Plex-Trakt-Scrobbler/issues/416, please install the [develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip) branch for a fix. Will try get this into a stable release this week.

**Closed** 2017-04-21 04:30 UTC
Labels: duplicate
