### ISSUE TITLE
Error syncing from plex

### ISSUE THREAD

**Issue by L0bit0** [trakt/Plex-Trakt-Scrobbler#158] opened 2015-01-05 12:57 UTC
Hi

i Just have installed trackt on my plex library. After some login issues, I was able to connect and i am trying to sync, but i can not sync. i got this error:
"Last run 6 seconds ago,taking 6 seconds, failed."

Anyway, i can see what i watching lively on trackt page, so i assume connection between plex and trackt is ok.

Just to confirm, sync, should send all information about watched TV shows and films to trackt, right?

I have tried to collect the trackt plugin log, but i can not find.

any idea?

thanks

**Comment by scottrobertson** [comment] 2015-01-05 13:15
Duplicate of #157?

**Comment by reokue** [comment] 2015-01-07 18:43
I had the same issue last night and I managed to fix it.

Change your username in the plugin from your username to the email associated with the  account.

**Comment by facted** [comment] 2015-01-07 20:02
I'm having the same issue with beta 9.1.2. Full log here: http://pastebin.com/8mQN2Ruk

I've tried changing username to e-mail  but it didn't work for me.

**Comment by L0bit0** [comment] 2015-01-08 09:07
Hi

I have added the eMail and told me invalid credentials.

Scott, not sure if is exactly the same issue you are referring to. anyway i have reviewed and i can not find a clear solution, please, can you clarify what do you thing the issue is and how to fix it?

thanks

**Comment by fuzeman** [comment] 2015-01-08 09:31
It's hard to really identify the specific cause of syncing to fail without the log files..

https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files should give you some idea of where they are located.

-------------------

@facted I'll look into that error tomorrow.

**Comment by NotExpectYet** [comment] 2015-01-08 11:46
I have exactly the same issue as this. Everytime I try to sync it fails after about a second. Has been working perfectly fine before this, well it has still be scrobbling but collections uploading is intermittent, it misses some. Then as said, manual sync fails everytime. Tried as been suggest above, replacing user name with email. 

My Log is here: https://drive.google.com/file/d/0B_FS3AeOwrCxVnQ4d1RFYlM4LXc/view?usp=sharing

**Comment by L0bit0** [comment] 2015-01-08 21:01
My logs here: https://app.box.com/s/kc9vy91jlfkvbh0vzhxn

Thanks

**Comment by fuzeman** [comment] 2015-01-09 00:13
@NotExpectYet @L0bit0 syncing would probably be more reliable with the latest beta version (https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-25#entry816952).

There still seems to be a number of issues with trakt.tv servers, this can cause syncing to fail as well (will just need to wait for the server issues to be resolved).

**Comment by facted** [comment] 2015-01-09 00:54
I'm on the latest beta and still have the issues i reported above, log is
included in my previous post.

**Comment by facted** [comment] 2015-01-09 18:30
I have the same issue as before on beta .9.1.5 . Log here: http://pastebin.com/R1z2qBhX

Perhaps I just need to somehow reset trakt, the database, etc...Is there anyway to do that? I've deleted the trakt plugin folder but it's clear the data isn't in there since I don't even have to re-enter my username/password for trakt.

**Comment by L0bit0** [comment] 2015-01-09 22:36
issue fixed with the beta on my side.

Thanks for your help.

**Comment by fuzeman** [comment] 2015-01-10 00:22
@facted looks like the "fix" wasn't quite right, will have another update available shortly.

The issue is a result of a (partly) corrupted backup file, the fix was designed to see this problem and handle it properly - instead of throwing an exception (and causing the sync to fail). *(note: this has nothing to do with your trakt.tv account)*

The likely cause of the 401 error (when you changed trakt accounts), is that the plugin hasn't actually tried to re-authenticate properly. *(will have this fixed in the next update)*

**Comment by fuzeman** [comment] 2015-01-10 01:00
@facted, try out the development version: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by facted** [comment] 2015-01-10 01:08
Works like a charm. Thanks so much!

**Comment by fuzeman** [comment] 2015-01-10 02:39
Glad that worked, will have those fixes included in a beta release later today.

**Comment by fuzeman** [comment] 2015-01-10 09:25
Fixes are now released in **v0.9.1.6-beta**: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-27#entry818966

**Closed** 2015-01-10 09:24 UTC
Labels: bug, syncing

**Comment by f3bruary22** [comment] 2015-01-31 23:30
I'm currently using 0.9.1.12-develop and getting this http://f3bruary.net/p/raw/mexirujubi
Do I need to switch to beta ? I'd rather use something a little more stable.
