### ISSUE TITLE
Cannot get trakt to sync

### ISSUE THREAD

**Issue by AHaymond** [trakt/Plex-Trakt-Scrobbler#466] opened 2017-10-12 18:39 UTC
I cannot get trakt to sync at all. I have the develop branch v1.3.2 installed and my logs keep repeating this.

```
2017-10-12 12:34:15,870 - plugin.managers.session.s_websocket (7f0bd67fc700) :  INFO (plugin.managers.session.s_websocket:1159) - Unable to find session with key 2
2017-10-12 12:34:33,837 - plugin.scrobbler.core.engine     (7f0bd67fc700) :  INFO (plugin.scrobbler.core.engine:1159) - Ignoring u'paused' event for <Session session_key: u'4:1', state: u'create'>, invalid state transition
```
I have authenticated and configured trakt to sync with Plex, but have 0 luck. Also when I click Full Sync, I get a "this channel is not responding" message on Plex.

PMS version: 1.9.4.4325
Linux distro

Please help.

**Comment by bbrendon** [comment] 2017-10-23 03:36
I Can't get it to sync either. I have lots of this error, but not the "...invalid state transition"

`plugin.managers.session.s_websocket (7fa6ab7fe700) :  INFO (plugin.managers.session.s_websocket:1159) - Unable to find session with key 1
`

**Comment by ScoobyJD** [comment] 2017-11-05 23:37
Looks like this hasnt been updated since the beginning of this year!?

**Comment by bbrendon** [comment] 2017-11-06 00:05
I finally got mine to sync by logging into the trakt website and removing the connection from that end and then re-authorizing. I have not checked the logs to see what errors exist if any.

**Comment by AlexMarcoDAngelo** [comment] 2018-02-04 17:09
Trakt.tv changed their authentication to OAuth. The plugin needs to be changed to account for that. But no word from the developer on this very important issue?

**Comment by rectifyer** [comment] 2018-02-05 15:36
In regards to @AlexMarcoDAngelo comment, please see https://github.com/trakt/Plex-Trakt-Scrobbler/issues/479. Nothing has changed with the Trakt Auth that requires an update to the plugin.

**Comment by mrfacu87** [comment] 2018-03-03 05:23
Experiencing same issue. Following

**Comment by mrfacu87** [comment] 2018-03-03 05:37
Ran Fiddler trace while reproducing the issue and got the following error:

<MediaContainer title1="Trakt.tv" art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" title2="Messages" size="12" identifier="com.plexapp.plugins.trakttv" sourceTitle="Trakt.tv" mediaTagPrefix="/system/bundle/media/flags/" prefsKey="/:/plugins/com.plexapp.plugins.trakttv/prefs">
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-default.png?t=1520052147" key="/video/trakt/messages/dismissAll" title="Dismiss all                   "/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=15" title="[Sentry] ProxyError: timed out"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=263" title="[Trakt.tv] OAuth must be provided (code: 401)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-exception.png?t=1520052147" key="/video/trakt/messages/view?error_id=264" title="[Exception] 'NoneType' object has no attribute '__getitem__'"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=51" title="[Trakt.tv] An existing connection was forcibly closed by the remote host (code: 10054)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=2" title="[Trakt.tv] Server unavailable (code: 502)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=6" title="[Trakt.tv] getaddrinfo failed (code: 11001)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=262" title="[Sentry] getaddrinfo failed (code: 11001)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=1" title="[Trakt.tv] The read operation timed out"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=261" title="[Trakt.tv] ConnectTimeoutError: Connection to api.trakt.tv timed out. (connect timeout=6.05)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=16" title="[Trakt.tv] Server overloaded (try again in 30s) (code: 504)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-default.png?t=1520052147" key="/video/trakt/messages/list?days=__NONE__&amp;viewed=__NONE__" title="View All                      "/>
</MediaContainer>

**Comment by mrfacu87** [comment] 2018-03-03 05:38
`<MediaContainer title1="Trakt.tv" art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" title2="Messages" size="12" identifier="com.plexapp.plugins.trakttv" sourceTitle="Trakt.tv" mediaTagPrefix="/system/bundle/media/flags/" prefsKey="/:/plugins/com.plexapp.plugins.trakttv/prefs">
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-default.png?t=1520052147" key="/video/trakt/messages/dismissAll" title="Dismiss all                   "/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=15" title="[Sentry] ProxyError: timed out"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=263" title="[Trakt.tv] OAuth must be provided (code: 401)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-exception.png?t=1520052147" key="/video/trakt/messages/view?error_id=264" title="[Exception] 'NoneType' object has no attribute '__getitem__'"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=51" title="[Trakt.tv] An existing connection was forcibly closed by the remote host (code: 10054)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=2" title="[Trakt.tv] Server unavailable (code: 502)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=6" title="[Trakt.tv] getaddrinfo failed (code: 11001)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=262" title="[Sentry] getaddrinfo failed (code: 11001)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=1" title="[Trakt.tv] The read operation timed out"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=261" title="[Trakt.tv] ConnectTimeoutError: Connection to api.trakt.tv timed out. (connect timeout=6.05)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-connection.png?t=1520052147" key="/video/trakt/messages/view?error_id=16" title="[Trakt.tv] Server overloaded (try again in 30s) (code: 504)"/>
  <Directory art="/:/plugins/com.plexapp.plugins.trakttv/resources/art-default.png?t=1520052147" thumb="/:/plugins/com.plexapp.plugins.trakttv/resources/icon-default.png?t=1520052147" key="/video/trakt/messages/list?days=__NONE__&amp;viewed=__NONE__" title="View All                      "/>
</MediaContainer>
`

**Comment by rectifyer** [comment] 2018-03-04 18:51
Have you tried the updates from #455? Looks like that adjusts some config variables which might allow the plugin to work properly on certain platforms.

**Comment by shwetkprabhat** [comment] 2018-03-04 21:48
Hi @rectifyer I have the same issue as #479, even if the auth model didnt change I see many people having the same issue now...something worth investigating or reopening #479

**Comment by shwetkprabhat** [comment] 2018-03-04 21:52
Never mind - I see your comments @rectifyer 

Authentication should work correctly now, I just pushed a Trakt fix for that. Let's use #484 to discuss the sentry.skipthe.net error. I reached out to the dev to ask if removing that code will cause another issues and pull requests are of course welcome!

**Comment by mrfacu87** [comment] 2018-03-05 03:25
I'm back up and running. Thank you.

**Comment by rectifyer** [comment] 2018-03-05 17:20
v1.3.3 should address this issue.

**Closed by rectifyer** 2018-03-05 17:20 UTC

**Comment by Kedryn** [comment] 2018-09-13 22:59
I'm using 1.3.3 and i'm experiencing the same error on one of my 2 plex server installation, the Windows one (the other is ubuntu and it's working).
