### ISSUE TITLE
Not working on Western Digital EX2

### ISSUE THREAD

**Issue by benceh90** [trakt/Plex-Trakt-Scrobbler#275] opened 2016-02-18 18:18 UTC
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/136701/com.plexapp.plugins.trakttv.log.txt)
I have copied the Trakttv.bundle to the following location /mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins

After restarting Plex, the trakt channel is not showing. Attached the logfile. Please help to proceed.

**Comment by gdolla** [comment] 2016-02-18 18:27
Maybe I should unplug the external hard drive from my router I was trying to set it up that I do something wrong?

**Comment by gdolla** [comment] 2016-02-18 18:27
Did someone just call me from you guys I didn't I wasn't sure where he was from

**Comment by fuzeman** [comment] 2016-02-18 22:50
@benceh90 Could you test the fix in this version of the plugin: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/arm-float-detection.zip. Just download that version, extract ```Trakttv.bundle``` into your ```Plug-ins``` directory and restart Plex Media Server.

Post the plugin log files again if it's still failing to startup.

----------------------------

@gdolla
> Maybe I should unplug the external hard drive from my router I was trying to set it up that I do something wrong?

This specific issue is related to the native libraries bundled with the plugin, not any issue with your hardware.

> Did someone just call me from you guys I didn't I wasn't sure where he was from

I can't speak for Trakt (this is a community project), but I didn't call you..

**Comment by rectifyer** [comment] 2016-02-18 23:03
No phones over at Trakt either :)

**Comment by benceh90** [comment] 2016-02-19 06:10
Hi,

tried it, but still not working. Logs:
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/137485/com.plexapp.plugins.trakttv.log.txt)

Thanks for the help :)

**Comment by benceh90** [comment] 2016-02-19 19:54
One additional info from my side: it has worked before ( I don't know whit which version of the plugin and which version of Plex Server, but it has surely worked before) - hope it helps.

**Comment by fuzeman** [comment] 2016-02-20 11:00
@benceh90 Could you test the changes in this version: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/arm-float-detection.zip

**Comment by benceh90** [comment] 2016-02-20 14:07
Unfortunately it doesn't help neither. 
Would you like to have any other log files (system.log from plex logs e.g.)?

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/139164/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment] 2016-02-20 21:19
@benceh90 Just pushed some more changes, so could you download the latest changes from here again: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/arm-float-detection.zip

----------------------

> Unfortunately it doesn't help neither.
> Would you like to have any other log files (system.log from plex logs e.g.)?

I know what the issue is, it's just a little difficult getting the fix working correctly without a system to directly test changes on. I think we are getting close to a fix though :smile:

**Comment by benceh90** [comment] 2016-02-21 07:53
Not there yet, but I am happy to provide what you need :)

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/139512/com.plexapp.plugins.trakttv.log.txt)

**Comment by gdolla** [comment] 2016-02-21 08:20
Thank you so much!!

**Comment by fuzeman** [comment] 2016-02-22 13:21
@benceh90 Just pushed more changes here: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/arm-float-detection.zip

Hopefully we are nearly there :smile:

**Comment by benceh90** [comment] 2016-02-22 16:09
Seems to be promising, but still not showing in Channels.
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/140917/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment] 2016-02-28 06:27
Could you try the `feature/libraries/cpu/marvell-pj4` branch ([download](https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/libraries/cpu/marvell-pj4.zip)) of the plugin. Please post the latest plugin log file if the plugin still doesn't startup correctly.

**Comment by benceh90** [comment] 2016-02-28 07:12
Still no joy. Thanks for your help again.
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/149779/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment] 2016-02-28 10:40
Just as a test, could you rename the ```marvell-pj4_64k``` folder to ```marvell-pj4``` in ```Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/armv7_sf```.

I'm thinking there might be some detection issues going on as the plugin is still starting up with the incorrect libraries.

**Comment by benceh90** [comment] 2016-02-28 13:11
Sure. Issue persists, here are the logs.
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/149910/com.plexapp.plugins.trakttv.txt)

**Comment by benceh90** [comment] 2016-02-28 13:13
Sorry, just needed to wait. It's working now. Huge thanks to you :)

**Comment by fuzeman** [comment] 2016-02-28 23:33
Great :smiley:, will make some changes to the plugin and have a final fix available to test likely tomorrow.

**Comment by fuzeman** [comment] 2016-02-29 09:31
Could you confirm the latest changes on the `feature/libraries/cpu/marvell-pj4` branch work correctly on your system, download it here: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/libraries/cpu/marvell-pj4.zip

You shouldn't need to rename any folder with this version, just want to make sure these changes work before including this in the next plugin release.

**Comment by gdolla** [comment] 2016-02-29 09:35
Yes sure, thank u!!!

**Comment by benceh90** [comment] 2016-02-29 17:16
@fuzeman I tried it and it's working :) Thanks again ;)

**Comment by fuzeman** [comment] 2016-03-01 12:27
Released in [v1.0.1.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.1.0)

**Closed by fuzeman** 2016-03-01 12:27 UTC
Labels: ARMv7, bug, in progress, libraries, western digital

**Comment by gdolla** [comment] 2016-06-19 10:50
try www.callapp.com/d free social Caller ID that identifies a billion
unknown callers

Mr GoLdNdOLLa
