### ISSUE TITLE
Not tracking shows with year attached in the title

### ISSUE THREAD

**Issue by pridit** [trakt/Plex-Trakt-Scrobbler#614] opened 2021-11-23 22:35 UTC
Strange issue I seem to be having with TV shows with an accompanying year in the title in the format of "Show (2021)". The plugin isn't matching any of these, and I have about half luck matching them correctly when the year is removed (however they do start scrobbling) as the year is obviously used to differentiate, at least for matching within Plex. I was under the impression the tracking was more sophisticated, so perhaps this is a fallback? Any ideas what I can do to fix scrobbling? Using the Plex TV Series scanner/agent.

**Comment by scoiattolo49** [comment] 2021-12-07 14:41
Duplicate of #596 

A patch solution is also provided there

**Closed as completed** 2021-12-07 15:02 UTC
