### ISSUE TITLE
Can't turn on Scrobble, other options disabled too

### ISSUE THREAD

**Issue by typistX** [trakt/Plex-Trakt-Scrobbler#229] opened 2015-09-16 22:27 UTC
Hello,

Just installed this (master), entered username and password and clicked "sync". Stuff did sync.

The main issue is that I can't change the "Scrobble" option from False to True or whatever that should be for it to automatically sync. Other options, like "Clean Collection", aren't accessible either. I've already tried removing my credentials and re-adding them.

Thanks!

**Comment by fuzeman** [comment] 2015-09-17 08:10
There isn't a way to disable certain plugin options, so this sounds like a bug in the client being used to configure the plugin.

Have you tried using Plex/Web to configure the trakt plugin? other plex clients are known to have bugs in plugin configuration.

----------------------------------------------

If you have tried configuring the plugin with Plex/Web, providing the plugin log files will help figure out what the issue is. See https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of the plugin log files

**Comment by typistX** [comment] 2015-09-17 08:20
> There isn't a way to disable certain plugin options, so this sounds like a bug in the client being used to configure the plugin.
>
> Have you tried using Plex/Web to configure the trakt plugin? other plex clients are known to have bugs in plugin configuration.

This worked. It's a checkbox, which apparently isn't a supported UI element in Kodi's Emby skin.

While I'm here, may I ask what settings are recommended for maximum "protection" to library status? I'm afraid to turn on "Push & Pull" on watched status for example, so Trakt doesn't override Plex for some weird reason. Any suggestions?

I'll close this one soon!

**Comment by fuzeman** [comment] 2015-09-17 08:42
> While I'm here, may I ask what settings are recommended for maximum "protection" to library status? I'm afraid to turn on "Push & Pull" on watched status for example, so Trakt doesn't override Plex for some weird reason. Any suggestions?

On the master/stable channel a "Pull" sync can only:
 - Mark items as watched in plex *([Trakttv.bundle/Contents/Code/sync/pull.py#L46](https://github.com/trakt/Plex-Trakt-Scrobbler/blob/master/Trakttv.bundle/Contents/Code/sync/pull.py#L46))*
 - Change the rating of items in plex *([Trakttv.bundle/Contents/Code/sync/pull.py#L69](https://github.com/trakt/Plex-Trakt-Scrobbler/blob/master/Trakttv.bundle/Contents/Code/sync/pull.py#L69))*

So you can't lose the "watched state" on items if there is any syncing issue. Worst case is items could be marked as watched or the rating of items could change (to match your trakt profile).

------------

I'm planning on implementing an automatic backup system so any syncing bugs that come up can be reverted easily, this feature will still be awhile away though.

**Closed** 2015-09-22 22:25 UTC
