### ISSUE TITLE
Pull from trakt failed (AttributeError: "'NoneType' object has no attribute 'rfind'").

### ISSUE THREAD

**Issue by Rumik** [trakt/Plex-Trakt-Scrobbler#211] opened 2015-07-27 20:06 UTC
Hi there,

Using the latest master release on the latest trakt server, running on my QNAP NAS. Getting this error when trying to sync down from trakt.tv.

Any ideas?

Thanks!

**Comment by fuzeman** [comment] 2015-07-28 23:16
Will look into this bug now.

**Comment by fuzeman** [comment] 2015-07-29 02:03
This issue should be fixed in [v0.9.1.28](https://forums.plex.tv/discussion/comment/982372/#Comment_982372), let me know if the issue is still happening after updating.

**Closed** 2015-07-29 02:03 UTC
Labels: bug, syncing

**Comment by mbze430** [comment] 2015-10-21 08:07
I am on 9.1.29-master and its been 12 days since I haven't been able to sync and the message I am getting is failed (AttributeError:"'NoneType' object has no attribute 'rfind'")
