### ISSUE TITLE
No longer scrobbling

### ISSUE THREAD

**Issue by Vallle** [trakt/Plex-Trakt-Scrobbler#380] opened 2016-12-14 16:55 UTC
Hi,

Been using the plugin for months, and it's been great. Latest weeks it has stopped scrobbling, and I'm not quite certain when it happened. I suppose it might have to do with updating the server? Anyhow, I've uploaded a log and would greatly appreciate if you could get back to me with some tips.

[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/652303/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment] 2016-12-15 01:54
Duplicate of https://github.com/trakt/Plex-Trakt-Scrobbler/issues/372, updating the plugin to [v1.1.0.7](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.7) will fix this issue.

**Closed** 2016-12-15 01:54 UTC
Labels: duplicate
