### ISSUE TITLE
Android TV support.

### ISSUE THREAD

**Issue by mikaelnt** [trakt/Plex-Trakt-Scrobbler#337] opened 2016-07-04 02:49 UTC
Hello,

I've just installed the recently released Plex server for Android TV on the Nvidia Shield. I have using Jidu before this with the Trakt script. I'm hoping this can be implemented.

Thanks for your efforts so far.

Regards

Michael Oliver

**Comment by fuzeman** [comment] 2016-07-04 21:49
Duplicate of #334, will try have this platform supported later this month.

**Closed** 2016-07-04 21:49 UTC
Labels: duplicate
